import { BellSchedule, IntermissionTrack, AudioZone, AdhanConfig, SystemAuditLog } from '../types';

export const initialBellSchedules: BellSchedule[] = [
  {
    id: '1',
    preset_id: 'preset-1',
    bell_time: '08:00',
    bell_type: 'ENTRY',
    label: 'طابور الصباح والنشيد الوطني',
    details: 'تم بنجاح وفق الخطة الصوتية مع عزل الصدى',
    duration_seconds: 20,
    target_zones: ['الساحة الرئيسية', 'الممرات الداخلية'],
    is_enabled: true,
  },
  {
    id: '2',
    preset_id: 'preset-1',
    bell_time: '08:15',
    bell_type: 'ENTRY',
    label: 'بداية الحصة الأولى',
    details: 'تم رن جرس الحصة الأولى لجميع الأقسام',
    duration_seconds: 8,
    target_zones: ['كافة المناطق'],
    is_enabled: true,
  },
  {
    id: '3',
    preset_id: 'preset-1',
    bell_time: '10:00',
    bell_type: 'BREAK',
    label: 'استراحة الصباح الأولى',
    details: 'الحدث التالي القادم - جرس تلقائي + تشغيل الرسائل التوعوية',
    duration_seconds: 10,
    target_zones: ['كافة المناطق'],
    is_enabled: true,
  },
  {
    id: '4',
    preset_id: 'preset-1',
    bell_time: '10:25',
    bell_type: 'WARNING',
    label: 'انتهاء الفسحة وعودة الفصول',
    details: 'جرس تنبيه عودة الطلاب إلى القاعات',
    duration_seconds: 6,
    target_zones: ['كافة المناطق'],
    is_enabled: true,
  },
  {
    id: '5',
    preset_id: 'preset-1',
    bell_time: '12:05',
    bell_type: 'BREAK',
    label: 'أذان الظهر الموحد',
    details: 'مقاطعة ذكية - أذان الحرم المكي الشريف مع دعاء ما بعد الأذان',
    duration_seconds: 180,
    target_zones: ['كافة المناطق'],
    is_enabled: true,
  },
  {
    id: '6',
    preset_id: 'preset-1',
    bell_time: '14:30',
    bell_type: 'EXIT',
    label: 'جرس انصراف الطلاب والمغادرة',
    details: 'جرس الانصراف الكامل وإخلاء المبنى المدرسي',
    duration_seconds: 15,
    target_zones: ['كافة المناطق'],
    is_enabled: true,
  },
];

export const initialIntermissionTracks: IntermissionTrack[] = [
  {
    id: 'track-1',
    session: 'MORNING_BREAK',
    category: 'PROVERB',
    title: 'فضل بر الوالدين',
    speaker_or_artist: 'حكمة اليوم • إلقاء الطالب أحمد المرزوقي',
    duration_seconds: 135,
    duration_formatted: '02:15',
    audio_url: 'https://cdn.smartbell.local/audio/proverb_parents.mp3',
    play_order: 1,
    is_active: true,
  },
  {
    id: 'track-2',
    session: 'MORNING_BREAK',
    category: 'STORY',
    title: 'قصة العالم ابن الهيثم',
    speaker_or_artist: 'محتوى إثرائي علمي • نادي العلوم والابتكار',
    duration_seconds: 230,
    duration_formatted: '03:50',
    audio_url: 'https://cdn.smartbell.local/audio/story_ibn_alhaytham.mp3',
    play_order: 2,
    is_active: true,
  },
  {
    id: 'track-3',
    session: 'MORNING_BREAK',
    category: 'NASHEED',
    title: 'نشيد العلم والنور (إنشاد كورال)',
    speaker_or_artist: 'إنشاد كورال المدرسة • نشيد حماسي وتربوي',
    duration_seconds: 270,
    duration_formatted: '04:30',
    audio_url: 'https://cdn.smartbell.local/audio/nasheed_knowledge.mp3',
    play_order: 3,
    is_active: true,
  },
  {
    id: 'track-4',
    session: 'MORNING_BREAK',
    category: 'DUAA',
    title: 'أذكار الصباح بصوت ندي وهادئ',
    speaker_or_artist: 'تلاوة وأذكار صباحية مباركة',
    duration_seconds: 252,
    duration_formatted: '04:12',
    audio_url: 'https://cdn.smartbell.local/audio/morning_adhkar.mp3',
    play_order: 4,
    is_active: true,
  },
];

export const initialAudioZones: AudioZone[] = [
  {
    id: 'zone-1',
    zone_code: 'ZONE_A',
    name: 'ساحة المدرسة والملاعب الخارجية',
    description: '8 مكبرات صوت IP نشطة مع عزل الصدى المفتوح',
    speaker_count: 8,
    status: 'ONLINE',
    volume: 85,
    is_muted: false,
    allow_morning_broadcast: true,
    ip_network: 'VLAN 20 (192.168.20.10-18)',
  },
  {
    id: 'zone-2',
    zone_code: 'ZONE_B',
    name: 'الممرات الداخلية والمطعم',
    description: '12 مكبر صوت سقفي موزع على الطوابق الثلاثة',
    speaker_count: 12,
    status: 'STANDBY',
    volume: 60,
    is_muted: false,
    allow_morning_broadcast: true,
    ip_network: 'VLAN 20 (192.168.20.20-32)',
  },
  {
    id: 'zone-3',
    zone_code: 'ZONE_C',
    name: 'قاعة الأساتذة والمكاتب الإدارية',
    description: '6 مكبرات صوت هادئة مخصصة فقط للأجراس والإشعارات الهامة',
    speaker_count: 6,
    status: 'MUTED',
    volume: 35,
    is_muted: true,
    allow_morning_broadcast: false,
    ip_network: 'VLAN 20 (192.168.20.40-46)',
  },
  {
    id: 'zone-4',
    zone_code: 'ZONE_D',
    name: 'المصلى المدرسي والملحقات',
    description: 'مخصص للأذان والتلاوات القرآنية وخطب صلاة الظهر',
    speaker_count: 4,
    status: 'ONLINE',
    volume: 90,
    is_muted: false,
    allow_morning_broadcast: false,
    ip_network: 'VLAN 20 (192.168.20.50-54)',
  },
];

export const initialAdhanConfig: AdhanConfig = {
  city: 'مراكش (المملكة المغربية)',
  latitude: 31.6295,
  longitude: -7.9811,
  calculation_method: 'وزارة الأوقاف والشؤون الإسلامية (Morocco Awqaf)',
  auto_interrupt: true,
  audio_url: 'أذان الحرم المكي الشريف (عالي النقاوة)',
  dua_after_athan: true,
};

export const initialLogs: SystemAuditLog[] = [
  {
    id: 'log-1',
    event_type: 'إقلاع النظام',
    description: 'تم بدء خدمة smartbell-daemon.service على بوابة Raspberry Pi 5 بنجاح',
    zone: 'العتاد المركزي',
    severity: 'INFO',
    created_at: '06:30:12 ص',
  },
  {
    id: 'log-2',
    event_type: 'مزامنة NTP',
    description: 'تم ضبط التوقيت الموحد محلياً بدقة متناهية عبر خادم NTP ومؤقت DS3231 RTC',
    zone: 'النظام',
    severity: 'INFO',
    created_at: '06:30:15 ص',
  },
  {
    id: 'log-3',
    event_type: 'جرس مجدول',
    description: 'تم تشغيل جرس طابور الصباح والنشيد الوطني تلقائياً لمدة 20 ثانية',
    zone: 'الساحة والملاعب',
    severity: 'INFO',
    created_at: '08:00:00 ص',
  },
  {
    id: 'log-4',
    event_type: 'جرس مجدول',
    description: 'تم تشغيل جرس بداية الحصة الأولى تلقائياً لكافة الزونات',
    zone: 'كافة المناطق',
    severity: 'INFO',
    created_at: '08:15:00 ص',
  },
  {
    id: 'log-5',
    event_type: 'بث إذاعي',
    description: 'بدء بث برنامج الصباح الإذاعي: نفحات تربوية إيمانية',
    zone: 'الساحة والممرات',
    severity: 'INFO',
    created_at: '08:20:00 ص',
  },
];
